services:
  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=bitly
      - POSTGRES_PASSWORD=bitly
      - POSTGRES_DB=bitly
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bitly -d bitly"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 512M

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --maxmemory 1gb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 1G

#  api:
#    build: .
#    container_name: api
#    depends_on:
#      postgres:
#        condition: service_healthy
#      redis:
#        condition: service_healthy
#    ports:
#      - "8080:8080"
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/bitly
#      - SPRING_DATASOURCE_USERNAME=bitly
#      - SPRING_DATASOURCE_PASSWORD=bitly
#      - SPRING_REDIS_HOST=redis
#      - SPRING_REDIS_PORT=6379
#    deploy:
#      resources:
#        limits:
#          memory: 1G
