spring:
  application:
    name: bitly
  datasource:
    url: jdbc:postgresql://localhost:5432/bitly
    username: bitly
    password: bitly
    driver: org.postgresql.Driver
  redis:
    host: localhost
    port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080