apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: k6
    user: admin
    secureJsonData:
      password: admin
    jsonData:
      httpMode: POST
      version: InfluxQL
      tlsSkipVerify: true
    isDefault: false
    editable: true
